title: Thomas Paul
email: nivintpaul[at]gmail[dot]com
description: >- # this means to ignore newlines until "baseurl:"
  Techie, Husband, Deep learning Enthusiast, Traveler, and Lifelong learner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tpk_in
github_username:  mrtpk
linkedin_username : mrtpk

show_excerpts: false
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-paginate-v2 # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#reading-pagination-meta-information

header_pages:
  # - about.markdown
  - posts.markdown

exclude:
  - assets/converters
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

pagination: # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages: # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
  enabled: false

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:year:month:title.html
# permalink: /:year/:month/:year:month:date_:title.html